Feature/add translation
ESGI-WEB/api-platform-challenge pull request #33
Opened 2023-10-30 15:33 UTC by mlaurie

close#29

2023-11-01 18:47 UTC, Nicolas-Wadoux-ESGI requested changes

2023-11-01 18:47 UTC, Nicolas-Wadoux-ESGI commented on api/config/packages/security.yaml
> +        - { path: ^/api/translations, roles: PUBLIC_ACCESS }
🔴 Seul le GET devrait être publique non ?

2023-11-01 18:47 UTC, Nicolas-Wadoux-ESGI commented on api/src/State/TranslationStateProcessor.php
> +        $data = [$data->getLanguage(), $data->getKey(), $data->getValue()];
🟠 Il faut pas vérifier qu'il n'y est pas déjà avant ?

2023-11-01 18:47 UTC, Nicolas-Wadoux-ESGI commented on api/src/State/TranslationStateProcessor.php
> +        $file = fopen($filePath, 'ab');
'ab' ? tu peux en faire une variable ou constante ou enum pour qu'on comprenne plus facilement ce que c'est stp ?

2023-11-01 18:47 UTC, Nicolas-Wadoux-ESGI commented on api/src/State/TranslationStateProvider.php
> +            $content = array_filter($content, function (Translation $translation) use ($language) {
Juste une idée comme ça, est ce que c'est plus simple de faire ce filtre qui risque de prendre du temps, ou de faire un fichier de traduction en anglais, et un en francais plutot ?

2023-11-01 18:47 UTC, Nicolas-Wadoux-ESGI commented on api/src/State/TranslationStateProvider.php
> +            $file = fopen($filePath, 'rb');
pareil que 'ab', ducoup un enum ce serait peut-être mieux ? ou des constantes comme TRANSLATION_CSV_PATH

2023-11-01 18:47 UTC, Nicolas-Wadoux-ESGI commented on api/src/Translations/translations.csv
> +en,superintendent,Superintendent
🟠 Il se passe quoi s'il y a une virgule dans le texte ?

2023-11-01 18:47 UTC, Nicolas-Wadoux-ESGI commented on api/src/ValueObject/Translation.php
> +        new GetCollection(),
Y'a que le get ? Pas de post donc tu utilises pas le stateprocessor ?

2023-11-01 18:47 UTC, Nicolas-Wadoux-ESGI commented on api/src/ValueObject/Translation.php
> +    normalizationContext: ['groups' => ['translation:read']],
Pour les groups, utiliser le GroupEnum

2023-11-01 18:47 UTC, Nicolas-Wadoux-ESGI commented on front/src/components/GlobalHeader.jsx
> -  brandTop = "e-commissariat",
plutot mettre brandTop = null et quand brandtop est null, remplacer par  t("headerBrandTop"), sinon ne pas toucher, pour garder la personnalisation au besoin du composant

2023-11-01 18:47 UTC, Nicolas-Wadoux-ESGI commented on front/src/components/ScriptedPasswordInput.jsx
> -    label = "Mot de passe",
De même que pour globalHeader

2023-11-01 18:47 UTC, Nicolas-Wadoux-ESGI commented on front/src/components/ScriptedPasswordInput.jsx
> +    const passwordLengthMessage = t("passwordLengthMessage");
🟠 Ici il faut utiliser l'interpolation, sinon on est obligé de changer la clé si on change le nombre, voir https://www.i18next.com/translation-function/interpolation
En gros ca devrait etre t('passwordLengthMessage', { length: 8 }) avec passwordLengthMessage = {{length}} caractères minimum

2023-11-01 18:47 UTC, Nicolas-Wadoux-ESGI commented on front/src/i18n.js
> +                        const parsedData = JSON.parse(data)["hydra:member"];
si hydra t'embête dans le cas de cette route, tu peux surement passer un header application/json (regarder le fichier api, j'ai fait ca dedans)
🔴 D'ailleurs, tu as mis le localhost en dur, il faut utiliser la variable du .env, ducoup faut vraiment voir si tu peux pas plutot utiliser l'objet api que j'ai créé, car tu auras automatiquement la gestion du .env et du header si besoin

2023-11-07 09:20 UTC, mlaurie commented on api/config/packages/security.yaml
> +        - { path: ^/api/translations, roles: PUBLIC_ACCESS }
Fait

2023-11-07 09:21 UTC, mlaurie commented on api/src/State/TranslationStateProcessor.php
> +        $data = [$data->getLanguage(), $data->getKey(), $data->getValue()];
J'ai fais qu'un Patch et Get finalement donc pas de vérif à faire.

2023-11-07 09:21 UTC, mlaurie commented on api/src/State/TranslationStateProcessor.php
> +        $file = fopen($filePath, 'ab');
Fait

2023-11-07 09:21 UTC, mlaurie commented on api/src/State/TranslationStateProvider.php
> +            $content = array_filter($content, function (Translation $translation) use ($language) {
J'ai fais 2 fichiers différents, niveau perf c'est effectivement mieux

2023-11-07 09:22 UTC, mlaurie commented on api/src/State/TranslationStateProvider.php
> +            $file = fopen($filePath, 'rb');
Fait

2023-11-07 09:22 UTC, mlaurie commented on api/src/Translations/translations.csv
> +en,superintendent,Superintendent
C'est pris en charge par fopen et des guillemets sont ajoutés autour de la traduction.

2023-11-07 09:23 UTC, mlaurie commented on api/src/ValueObject/Translation.php
> +        new GetCollection(),
Fait, j'utilise patch et post.

2023-11-07 09:24 UTC, mlaurie commented on api/src/ValueObject/Translation.php
> +    normalizationContext: ['groups' => ['translation:read']],
Fait

2023-11-07 09:41 UTC, mlaurie commented on front/src/components/ScriptedPasswordInput.jsx
> +    const passwordLengthMessage = t("passwordLengthMessage");
Fait

2023-11-07 17:23 UTC, mlaurie commented on front/src/i18n.js
> +                        const parsedData = JSON.parse(data)["hydra:member"];
fait

2023-11-18 20:35 UTC, Nicolas-Wadoux-ESGI requested changes

2023-11-18 20:35 UTC, Nicolas-Wadoux-ESGI commented on api/src/ValueObject/Translation.php
> +            uriTemplate: '/translations/{language}/{key}',
security: "is_granted('" . RolesEnum::ADMIN->value . "')"

2023-11-19 10:50 UTC, merged